"""
Solver for University Examination Timetabling using Ant Colony Optimization and Local Search
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AcoParams', 'Ant', 'AntColony', 'Hyperparams', 'LsParams']
class AcoParams:
    def __init__(self) -> None:
        ...
    @property
    def alpha(self) -> float:
        ...
    @alpha.setter
    def alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def beta(self) -> float:
        ...
    @beta.setter
    def beta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_ants(self) -> int:
        ...
    @num_ants.setter
    def num_ants(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def num_iters(self) -> int:
        ...
    @num_iters.setter
    def num_iters(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def penalty_decay_base(self) -> float:
        ...
    @penalty_decay_base.setter
    def penalty_decay_base(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def rho(self) -> float:
        ...
    @rho.setter
    def rho(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def tau_max(self) -> float:
        ...
    @tau_max.setter
    def tau_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def tau_min(self) -> float:
        ...
    @tau_min.setter
    def tau_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Ant:
    @property
    def fitness(self) -> float:
        ...
    @property
    def schedule(self) -> list[int]:
        ...
class AntColony:
    def __init__(self, arg0: Hyperparams, arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], arg2: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def run(self, arg0: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], None]) -> None:
        ...
    def run_one_iteration(self) -> float:
        ...
    @property
    def global_best(self) -> Ant:
        ...
class Hyperparams:
    aco: AcoParams
    ls: LsParams
    def __init__(self) -> None:
        ...
class LsParams:
    def __init__(self) -> None:
        ...
    @property
    def max_improvements(self) -> int:
        ...
    @max_improvements.setter
    def max_improvements(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def patience(self) -> int:
        ...
    @patience.setter
    def patience(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def prob_1_move(self) -> float:
        ...
    @prob_1_move.setter
    def prob_1_move(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
