"""
Solver for University Examination Timetabling using Ant Colony Optimization and Local Search
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AcoParams', 'AntColony', 'EvalParams', 'Hyperparams', 'LsParams', 'Solution']
class AcoParams:
    def __init__(self, _num_iters: typing.SupportsInt | typing.SupportsIndex = 100, _num_ants: typing.SupportsInt | typing.SupportsIndex = 10, _alpha: typing.SupportsFloat | typing.SupportsIndex = 1.0, _beta: typing.SupportsFloat | typing.SupportsIndex = 2.0, _rho: typing.SupportsFloat | typing.SupportsIndex = 0.1, _tau_min: typing.SupportsFloat | typing.SupportsIndex = 0.01, _tau_max: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> None:
        ...
    @property
    def alpha(self) -> float:
        ...
    @alpha.setter
    def alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def beta(self) -> float:
        ...
    @beta.setter
    def beta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_ants(self) -> int:
        ...
    @num_ants.setter
    def num_ants(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def num_iters(self) -> int:
        ...
    @num_iters.setter
    def num_iters(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def rho(self) -> float:
        ...
    @rho.setter
    def rho(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def tau_max(self) -> float:
        ...
    @tau_max.setter
    def tau_max(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def tau_min(self) -> float:
        ...
    @tau_min.setter
    def tau_min(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class AntColony:
    def __init__(self, arg0: Hyperparams, arg1: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], arg2: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg3: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def run(self, arg0: collections.abc.Callable[[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex], None]) -> None:
        ...
    def run_one_iteration(self) -> float:
        ...
    @property
    def global_best_fitness(self) -> float:
        ...
    @property
    def global_best_schedule(self) -> list[int]:
        ...
class EvalParams:
    def __init__(self, _penalty_decay_base: typing.SupportsFloat | typing.SupportsIndex = 2.0) -> None:
        ...
    @property
    def penalty_decay_base(self) -> float:
        ...
    @penalty_decay_base.setter
    def penalty_decay_base(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Hyperparams:
    aco: AcoParams
    eval: EvalParams
    ls: LsParams
    def __init__(self, _eval: EvalParams = ..., _aco: AcoParams = ..., _ls: LsParams = ...) -> None:
        ...
class LsParams:
    def __init__(self, _prob_1_move: typing.SupportsFloat | typing.SupportsIndex = 0.5, _max_improvements: typing.SupportsInt | typing.SupportsIndex = 10, _patience: typing.SupportsInt | typing.SupportsIndex = 100) -> None:
        ...
    @property
    def max_improvements(self) -> int:
        ...
    @max_improvements.setter
    def max_improvements(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def patience(self) -> int:
        ...
    @patience.setter
    def patience(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def prob_1_move(self) -> float:
        ...
    @prob_1_move.setter
    def prob_1_move(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Solution:
    @property
    def fitness(self) -> float:
        ...
    @property
    def schedule(self) -> list[int]:
        ...
